### ISSUE TITLE
Problem checking if given string is equal to a JSONObject's property

### ISSUE THREAD

**Issue by ghost** [beders/Resty#47]
I'm trying to loop over a json array to check if a given string is equal to the current JSONObject's property.

Here's the result from the GET `/accounts` request:

``` json
[
  {
    "username": "admin",
    "password": "password"
  },
  {
    "username": "a2ko",
    "password": "MABUHAY"
  },
  {
    "username": "bitoy",
    "password": "maytuko"
  }
]
```

Here's the method I'm having a problem with:

``` java
private void login(String username) {
  JSONArray accounts = null;
  boolean found = false;
    try {
      accounts = r.json(apiUrl + "/accounts").array();
    } catch (IOException | JSONException e) {
      e.printStackTrace();
    }

    for (int i = 0; i < accounts.length(); i++) {
      try {
        if (accounts.getJSONObject(i).getString("username") == username) {
          found = true;
          break;
        }
      } catch (JSONException e) {
      e.printStackTrace();
    }
  }
  System.out.println(found); // check if user was found
}
```

I can guarantee that the `username` parameter is not null.

**Comment by ghost** [comment]
Solved it somehow by directly comparing String instances.

``` java
accounts = r.json(apiUrl + "/accounts").array();

for (int i = 0; i < accounts.length(); i++) {
  String _username = accounts.getJSONObject(i).getString("username").toString();
  System.out.println(_username);
  if (_username.equals(txtUsername.getText().toString())) {
    found = true;
    break;
  }
}
```

**Comment by beders** [comment]
Try getString("username").equals(username);

```
  From: Vincent Kyle Eusebio <notifications@github.com>
```

 To: beders/Resty Resty@noreply.github.com 
 Sent: Friday, February 12, 2016 1:54 AM
 Subject: [Resty] Problem checking if given string is equal to a JSONObject's property (#47)

I'm trying to loop over a json array to check if a given string is equal to the current JSONObject's property.Here's the result from the GET /accounts request:[
  {
    "username": "admin",
    "password": "password"
  },
  {
    "username": "a2ko",
    "password": "MABUHAY"
  },
  {
    "username": "bitoy",
    "password": "maytuko"
  }
]Here's the method I'm having a problem with:private void login(String username) {
  JSONArray accounts = null;
  boolean found = false;
    try {
      accounts = r.json(apiUrl + "/accounts").array();
    } catch (IOException | JSONException e) {
      e.printStackTrace();
    }

```
for (int i = 0; i < accounts.length(); i++) {
  try {
    if (accounts.getJSONObject(i).getString("username") == username) {
      found = true;
      break;
    }
  } catch (JSONException e) {
  e.printStackTrace();
}
```

  }
  System.out.println(found);
}—
